python2-stylecheck:
  image: python:2.7-alpine
  stage: test
  script:
    - pip install flake8
    - flake8
  tags:
    - docker

python2-tests:
  image: python:2.7-alpine
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test
  tags:
    - docker
